name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]  

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ROOT_PASSWORD: zhenyang7838675
          MYSQL_DATABASE: clod01
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 17
            uses: actions/setup-java@v2
            with:
             java-version: '17'
             distribution: 'adopt'

          - name: Set Environment Variable for Profile
            run: echo "SPRING_PROFILES_ACTIVE=ci" >> $GITHUB_ENV

          - name: Build with Maven
            run: mvn -B package --file pom.xml

          - name: Run Integration Tests
            run: mvn verify
#          - name: Cache Maven packages
#            uses: actions/cache@v2
#            with:
#               path: ~/.m2
#               key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#               restore-keys: ${{ runner.os }}-m2
#
#          - name: Run Integration Tests in helloWorld
#            run:
#             mvn clean test -Dspring.datasource.url=jdbc:mysql://localhost:3306/clod01 -Dspring.datasource.username=root -Dspring.datasource.password=zhenyang7838675
#
